export const MATRIX_BASE_URL = MATRIX_ENTRANCE


export const DYNO_POLL_WAIT = 'DYNO_POLL_WAIT'
export const DYNO_POLL_SUCC = 'DYNO_POLL_SUCC'
export const DYNO_POLL_FAIL = 'DYNO_POLL_FAIL'

export const DYNO_POLL_RESET_WAIT = 'DYNO_POLL_RESET_WAIT'
export const DYNO_POLL_RESET_SUCC = 'DYNO_POLL_RESET_SUCC'
export const DYNO_POLL_RESET_FAIL = 'DYNO_POLL_RESET_FAIL'

export const DYNO_SHOW_HELP	= 'DYNO_SHOW_HELP'
export const DYNO_HIDE_HELP	= 'DYNO_HIDE_HELP'

export const DYNO_SHOW_GRAPH	= 'DYNO_SHOW_GRAPH'
export const DYNO_HIDE_GRAPH	= 'DYNO_HIDE_GRAPH'

export const DYNO_WHOAMI_WAIT	= 'DYNO_WHOAMI_WAIT'
export const DYNO_WHOAMI_SUCC	= 'DYNO_WHOAMI_SUCC'
export const DYNO_WHOAMI_FAIL	= 'DYNO_WHOAMI_FAIL'

export const DYNO_AUTHENTICATE_WAIT	= 'DYNO_AUTHENTICATE_WAIT'
export const DYNO_AUTHENTICATE_SUCC	= 'DYNO_AUTHENTICATE_SUCC'
export const DYNO_AUTHENTICATE_FAIL	= 'DYNO_AUTHENTICATE_FAIL'

export const DYNO_UNAUTHENTICATE_WAIT	= 'DYNO_UNAUTHENTICATE_WAIT'
export const DYNO_UNAUTHENTICATE_SUCC	= 'DYNO_UNAUTHENTICATE_SUCC'
export const DYNO_UNAUTHENTICATE_FAIL	= 'DYNO_UNAUTHENTICATE_FAIL'

export const DYNO_NAMESPACE_LIST_WAIT = 'DYNO_NAMESPACE_LIST_WAIT'
export const DYNO_NAMESPACE_LIST_SUCC = 'DYNO_NAMESPACE_LIST_SUCC'
export const DYNO_NAMESPACE_LIST_FAIL = 'DYNO_NAMESPACE_LIST_FAIL'

export const DYNO_PROJECT_LIST_WAIT = 'DYNO_PROJECT_LIST_WAIT'
export const DYNO_PROJECT_LIST_SUCC = 'DYNO_PROJECT_LIST_SUCC'
export const DYNO_PROJECT_LIST_FAIL = 'DYNO_PROJECT_LIST_FAIL'

export const DYNO_BRANCH_LIST_WAIT = 'DYNO_BRANCH_LIST_WAIT'
export const DYNO_BRANCH_LIST_SUCC = 'DYNO_BRANCH_LIST_SUCC'
export const DYNO_BRANCH_LIST_FAIL = 'DYNO_BRANCH_LIST_FAIL'

export const DYNO_PROFILE_LIST_WAIT = 'DYNO_PROFILE_LIST_WAIT'
export const DYNO_PROFILE_LIST_SUCC = 'DYNO_PROFILE_LIST_SUCC'
export const DYNO_PROFILE_LIST_FAIL = 'DYNO_PROFILE_LIST_FAIL'

export const DYNO_COMMIT_LIST_WAIT = 'DYNO_COMMIT_LIST_WAIT'
export const DYNO_COMMIT_LIST_SUCC = 'DYNO_COMMIT_LIST_SUCC'
export const DYNO_COMMIT_LIST_FAIL = 'DYNO_COMMIT_LIST_FAIL'

export const DYNO_OPEN_NAMESPACE		= 'DYNO_OPEN_NAMESPACE'
export const DYNO_OPEN_NAMESPACE_WAIT	= 'DYNO_OPEN_NAMESPACE_WAIT'
export const DYNO_OPEN_NAMESPACE_SUCC	= 'DYNO_OPEN_NAMESPACE_SUCC'
export const DYNO_OPEN_NAMESPACE_FAIL	= 'DYNO_OPEN_NAMESPACE_FAIL'

export const DYNO_OPEN_PROJECT		= 'DYNO_OPEN_PROJECT'
export const DYNO_OPEN_PROJECT_WAIT	= 'DYNO_OPEN_PROJECT_WAIT'
export const DYNO_OPEN_PROJECT_SUCC	= 'DYNO_OPEN_PROJECT_SUCC'
export const DYNO_OPEN_PROJECT_FAIL	= 'DYNO_OPEN_PROJECT_FAIL'

export const DYNO_OPEN_BRANCH_WAIT	= 'DYNO_OPEN_BRANCH_WAIT'
export const DYNO_OPEN_BRANCH_SUCC	= 'DYNO_OPEN_BRANCH_SUCC'
export const DYNO_OPEN_BRANCH_FAIL	= 'DYNO_OPEN_BRANCH_FAIL'

export const DYNO_OPEN_PROFILE_WAIT	= 'DYNO_OPEN_PROFILE_WAIT'
export const DYNO_OPEN_PROFILE_SUCC	= 'DYNO_OPEN_PROFILE_SUCC'
export const DYNO_OPEN_PROFILE_FAIL	= 'DYNO_OPEN_PROFILE_FAIL'

export const DYNO_COMPILE_WAIT = 'DYNO_COMPILE_WAIT'
export const DYNO_COMPILE_SUCC = 'DYNO_COMPILE_SUCC'
export const DYNO_COMPILE_FAIL = 'DYNO_COMPILE_FAIL'

export const DYNO_GETFILE_WAIT = 'DYNO_GETFILE_WAIT'
export const DYNO_GETFILE_SUCC = 'DYNO_GETFILE_SUCC'
export const DYNO_GETFILE_FAIL = 'DYNO_GETFILE_FAIL'

export const DYNO_HDFS_LS_WAIT = 'DYNO_HDFS_LS_WAIT'
export const DYNO_HDFS_LS_SUCC = 'DYNO_HDFS_LS_SUCC'
export const DYNO_HDFS_LS_FAIL = 'DYNO_HDFS_LS_FAIL'

export const DYNO_GET_OOZIE_COORDINATOR_INFO_WAIT = 'DYNO_GET_OOZIE_COORDINATOR_INFO_WAIT'
export const DYNO_GET_OOZIE_COORDINATOR_INFO_SUCC = 'DYNO_GET_OOZIE_COORDINATOR_INFO_SUCC'
export const DYNO_GET_OOZIE_COORDINATOR_INFO_FAIL = 'DYNO_GET_OOZIE_COORDINATOR_INFO_FAIL'

export const DYNO_GET_OOZIE_JOBS_WAIT = 'DYNO_GET_OOZIE_JOBS_WAIT'
export const DYNO_GET_OOZIE_JOBS_SUCC = 'DYNO_GET_OOZIE_JOBS_SUCC'
export const DYNO_GET_OOZIE_JOBS_FAIL = 'DYNO_GET_OOZIE_JOBS_FAIL'

export const DYNO_DEPLOY_WAIT = 'DYNO_DEPLOY_WAIT'
export const DYNO_DEPLOY_SUCC = 'DYNO_DEPLOY_SUCC'
export const DYNO_DEPLOY_FAIL = 'DYNO_DEPLOY_FAIL'

const STATUS_SUCCESS = 'SUCCESS'
const STATUS_FAILURE = 'FAILURE'

const CODE_SUCCESS = 0


export function succ(data) {
	return {
		data: data,
		status: STATUS_SUCCESS,
		code: CODE_SUCCESS,
		msg: ''
	}
}

export function fail(msg) {
	return {
		data: null,
		status: STATUS_FAILURE,
		code: CODE_SUCCESS,
		msg: msg
	}
}
