#!/bin/sh

NAMESPACE={{NAMESPACE}}
PROJECT={{PROJECT}}

refname="$1"
oldrev="$2"
newrev="$3"

# --- Safety check
if [ -z "$GIT_DIR" ]; then
	echo "Don't run this script from the command line." >&2
	echo " (if you want, you could supply GIT_DIR then run" >&2
	echo "  $0 <ref> <oldrev> <newrev>)" >&2
	exit 1
fi

if [ -z "$refname" -o -z "$oldrev" -o -z "$newrev" ]; then
	echo "usage: $0 <ref> <oldrev> <newrev>" >&2
	exit 1
fi

# if $newrev is 0000...0000, it's a commit to delete a ref.
zero="0000000000000000000000000000000000000000"
if [ "$newrev" = "$zero" ]; then
	newrev_type=delete
	exit 0
else
	newrev_type=$(git cat-file -t $newrev)
fi

set -e

mkdir -p /tmp/datamot/tmp
WP=$(mktemp -d --tmpdir=/tmp/datamot/tmp/)
WD=$(basename $WP)

echo
git worktree add $WP $newrev > /dev/null
datamot --compile $WP $NAMESPACE $PROJECT $(basename $refname) $newrev
rm -rf /tmp/datamot/tmp/$WD
git worktree prune
echo

exit 0
